/**
 * dsh-ide — "加入 VCS 管理" 弹窗（先选后初始化）。
 *
 * 弹窗展示工作区文件树：勾选 = 加入 git；不勾选 = 忽略（可选写入生成的
 * .gitignore）。可填初始分支名并选择是否生成 .gitignore。确认后才执行
 * `git init -b <branch>` →（可选）写 .gitignore → `git add` 选中文件。
 */

import { useEffect, useState, type ReactElement } from "react";
import { call } from "./ideApi";
import { ChangeTree, type ChangeLeaf } from "./ChangeTree";

interface Props {
  root: string;
  onClose: () => void;
  onNotify: (message: string) => void;
  onDone: (added: number, branch: string) => void;
}

const SKIP_DIRS = new Set([".git", "node_modules", "target", "dist", ".idea", ".vscode"]);

export function InitGitDialog({ root, onClose, onNotify, onDone }: Props): ReactElement {
  const [leaves, setLeaves] = useState<ChangeLeaf[]>([]);
  const [loading, setLoading] = useState(true);
  const [picked, setPicked] = useState<Record<string, boolean>>({});
  const [branch, setBranch] = useState("");
  const [makeIgnore, setMakeIgnore] = useState(true);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    let alive = true;
    void (async () => {
      const out: ChangeLeaf[] = [];
      const visited = new Set<string>();
      const walk = async (dir: string, depth: number): Promise<void> => {
        if (!alive || depth > 5 || visited.size > 3000) return;
        visited.add(dir);
        let entries: Array<{ name: string; kind: "file" | "dir"; path: string }> = [];
        try {
          const r = (await call("fs.list", { path: dir })) as { entries: typeof entries };
          entries = r.entries;
        } catch {
          return;
        }
        for (const e of entries) {
          if (e.name.startsWith(".")) continue;
          if (e.kind === "dir") {
            if (!SKIP_DIRS.has(e.name)) await walk(e.path, depth + 1);
          } else {
            const rel = e.path.slice(root.length).replace(/^[\\/]+/, "").replace(/\\/g, "/");
            if (rel) out.push({ key: rel, code: "", path: rel });
          }
        }
      };
      await walk(root, 0);
      if (alive) {
        out.sort((a, b) => a.path.localeCompare(b.path));
        setLeaves(out);
        setLoading(false);
      }
    })();
    return () => {
      alive = false;
    };
  }, [root]);

  useEffect(() => {
    const onKey = (e: KeyboardEvent): void => {
      if (e.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKey, true);
    return () => window.removeEventListener("keydown", onKey, true);
  }, [onClose]);

  const added = leaves.filter((l) => picked[l.key] !== false);
  const ignored = leaves.filter((l) => picked[l.key] === false);
  const count = added.length;
  const allPicked = leaves.length > 0 && added.length === leaves.length;

  const absOf = (rel: string): string => root.replace(/[\\/]+$/, "") + "\\" + rel.replace(/\//g, "\\");

  const confirmInit = async (): Promise<void> => {
    if (count === 0) return;
    setBusy(true);
    try {
      const branchName = branch.trim() || "main";
      await call("git.init", { branch: branchName });
      // Create .gitignore with the ignored paths before staging.
      if (makeIgnore) {
        const lines = ignored.map((l) => "/" + l.path);
        const text = ["# generated by dsh-ide", ...lines, ""].join("\n");
        const giPath = root.replace(/[\\/]+$/, "") + "\\.gitignore";
        await call("fs.write", { path: giPath, text });
      }
      await call("git.addMany", { repo: root, files: added.map((l) => absOf(l.key)) });
      onDone(count, branchName);
      onClose();
    } catch (err) {
      onNotify(err instanceof Error ? err.message : String(err));
      setBusy(false);
    }
  };

  return (
    <div
      onMouseDown={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
      style={{
        position: "fixed",
        inset: 0,
        zIndex: 300,
        background: "rgba(0,0,0,.22)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
      }}
    >
      <div
        style={{
          width: 640,
          maxWidth: "94vw",
          maxHeight: "84vh",
          display: "flex",
          flexDirection: "column",
          padding: 16,
          borderRadius: 14,
          background: "var(--dsw-specific-menu, var(--dsw-alias-bg-layer-2, #fff))",
          boxShadow: "0 18px 56px rgba(0,0,0,.2)",
          color: "var(--dsw-alias-label-primary, #0f1115)",
        }}
      >
        <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10, flex: "none" }}>
          <span style={{ fontSize: 14, fontWeight: 600 }}>加入 VCS 管理</span>
          <span style={{ fontSize: 11, color: "var(--dsw-alias-label-tertiary, #81858c)", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{root}</span>
          <button type="button" aria-label="关闭" onClick={onClose} style={{ marginLeft: "auto", width: 26, height: 26, border: "none", borderRadius: 6, cursor: "pointer", background: "transparent", color: "var(--dsw-alias-label-secondary, #61666b)" }}>
            ✕
          </button>
        </div>

        {/* options */}
        <div style={{ display: "flex", alignItems: "center", gap: 10, paddingBottom: 8, borderBottom: "1px solid var(--dsw-alias-border-l1, rgba(0,0,0,.06))", flex: "none" }}>
          <label style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 12.5 }}>
            初始分支名
            <input
              value={branch}
              onChange={(e) => setBranch(e.target.value)}
              placeholder="main（默认）"
              style={{
                width: 140,
                padding: "4px 8px",
                fontSize: 12.5,
                borderRadius: 6,
                border: "1px solid var(--dsw-alias-border-l1, rgba(0,0,0,.14))",
                background: "var(--dsw-alias-bg-base, #fff)",
                color: "var(--dsw-alias-label-primary, #0f1115)",
              }}
            />
          </label>
          <label style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 12.5, cursor: "pointer" }}>
            <input type="checkbox" checked={makeIgnore} onChange={(e) => setMakeIgnore(e.target.checked)} />
            创建 .gitignore（未勾选的文件写入忽略规则）
          </label>
        </div>

        {/* file tree with include/ignore */}
        <div style={{ flex: 1, minHeight: 0, overflow: "auto", margin: "8px 0" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "2px 4px 6px" }}>
            <button
              type="button"
              onClick={() => {
                const next: Record<string, boolean> = {};
                if (!allPicked) for (const l of leaves) next[l.key] = true;
                setPicked(next);
              }}
              style={{ fontSize: 12, cursor: "pointer", border: "none", borderRadius: 6, padding: "3px 10px", background: "var(--dsw-alias-interactive-bg-hover, rgba(0,0,0,.07))", color: "var(--dsw-alias-label-primary, #0f1115)" }}
            >
              {allPicked ? "全不选" : "全选"}
            </button>
            <span style={{ fontSize: 11, color: "var(--dsw-alias-label-tertiary, #81858c)" }}>
              勾选=加入（{added.length}）· 未勾选=忽略（{ignored.length}）
            </span>
          </div>
          {loading ? (
            <div style={{ padding: 12, fontSize: 12.5, color: "var(--dsw-alias-label-tertiary, #81858c)" }}>扫描工作区…</div>
          ) : leaves.length === 0 ? (
            <div style={{ padding: 12, fontSize: 12.5, color: "var(--dsw-alias-label-secondary, #61666b)" }}>（工作区为空）</div>
          ) : (
            <ChangeTree checkable checked={picked} onToggle={(key) => setPicked((m) => ({ ...m, [key]: m[key] === false }))} leaves={leaves} />
          )}
        </div>

        <div style={{ display: "flex", justifyContent: "flex-end", gap: 8, flex: "none" }}>
          <button type="button" onClick={onClose} style={{ padding: "6px 14px", fontSize: 12.5, cursor: "pointer", border: "1px solid var(--dsw-alias-border-l1, rgba(0,0,0,.1))", borderRadius: 8, background: "transparent", color: "var(--dsw-alias-label-primary, #0f1115)" }}>
            取消
          </button>
          <button
            type="button"
            disabled={count === 0 || busy}
            onClick={() => void confirmInit()}
            style={{ padding: "6px 16px", fontSize: 12.5, cursor: count === 0 || busy ? "not-allowed" : "pointer", border: "none", borderRadius: 8, background: "var(--dsw-alias-interactive-bg-hover, rgba(0,0,0,.1))", color: "var(--dsw-alias-label-primary, #0f1115)", opacity: count === 0 || busy ? 0.5 : 1 }}
          >
            {busy ? "初始化中…" : `初始化并加入（${count}）`}
          </button>
        </div>
      </div>
    </div>
  );
}
